
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 10 22:05:20 GMT-03:00 2008
//----------------------------------------------------

package pl747.sintatico;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 15;
  public static final int LBRACKET = 6;
  public static final int CHAR = 37;
  public static final int CONST = 35;
  public static final int ATRIBUTION = 5;
  public static final int LPAREN = 8;
  public static final int SEMI = 2;
  public static final int INT = 36;
  public static final int LESS = 22;
  public static final int FOR = 30;
  public static final int MINUS = 13;
  public static final int REF = 33;
  public static final int MEQUAL = 25;
  public static final int CHARACTER = 45;
  public static final int RPAREN = 9;
  public static final int IDENTIFICADOR = 43;
  public static final int NOT = 19;
  public static final int AND = 17;
  public static final int OR = 18;
  public static final int PLUS = 12;
  public static final int MAIN = 40;
  public static final int IF = 26;
  public static final int DOT = 4;
  public static final int BOOLEAN = 38;
  public static final int EOF = 0;
  public static final int BOOLEAN_VALOR = 46;
  public static final int RETURN = 41;
  public static final int RBRACKET = 7;
  public static final int EQUAL = 20;
  public static final int error = 1;
  public static final int COMA = 3;
  public static final int NUMBER = 42;
  public static final int MOD = 16;
  public static final int VOID = 39;
  public static final int TIMES = 14;
  public static final int LBRACE = 10;
  public static final int ELSE = 27;
  public static final int LEQUAL = 24;
  public static final int TO = 31;
  public static final int WHILE = 28;
  public static final int NEQUAL = 21;
  public static final int RBRACE = 11;
  public static final int STRING = 44;
  public static final int DOWNTO = 32;
  public static final int STRUCT = 34;
  public static final int MORE = 23;
  public static final int DO = 29;
}

